*Sets*

Set     YEAR    /2015*2050/;
Set     TECHNOLOGY      /
        OIL 'Crude Oil'
        BIO 'Biomass'
        COA 'Coal'
        LFO 'Light Fuel Oil'
        NGS 'Natural Gas'
        HFO 'Heavy Fuel Oil'
        SOL 'Solar'
        HYD 'Hydro'
        WND 'Wind'
        URN 'Uranium'
        GEO 'Geothermal'
        ELC001  'Electricity from Power Plants'
        ELC002  'Electricity after Transmission'
        ELCOO3  'Electricity after Distibution'
        ELCEV   'ELectricity for EVs'
        TRAMCY  'Motorcycle Transport Demand'
        TRACAR  'Car Transport Demand'
        TARBUS  'Bus + Rail Transport Demand'
        INDELC  'Industrial Electricity Demand'
        INDHEH  'Industrial High Heat Demand'
        INDHEL  'Industrial Low Heat Demand'
        RESELC  'Residential ELectricity Demand'
        RESCKN  'Residential Cooking Demand'
        RESHEL  'Residential Low Heat Demand'
        COMELC  'Commercial Electricity Demand'
        COMHEL  'Commercial Low Heat Demand'
        COM027  'Additional Fuel'
        COM028  'Additional Fuel'
        COM029  'Additional Fuel'
        COM030  'Additional Fuel'
        COM031  'Additional Fuel'
        COM032  'Additional Fuel'   
        COM033  'Additional Fuel'
        COM034  'Additional Fuel'
        COM035  'Additional Fuel'
        COM036  'Additional Fuel'
        COM037  'Additional Fuel'
        COM038  'Additional Fuel'
        COM039  'Additional Fuel'
        COM040  'Additional Fuel'
        COM041  'Additional Fuel'
        COM042  'Additional Fuel'
        COM043  'Additional Fuel'
        COM044  'Additional Fuel'
        COM045  'Additional Fuel'
        COM046  'Additional Fuel'
        COM047  'Additional Fuel'
        COM048  'Additional Fuel'
        COM049  'Additional Fuel'
        COM050  'Additional Fuel'
    /;


sdsaddasdsa